model_config:
  movie_mcan:
    losses:
    - type: triple_logit_bce
    # image_feature_dim: 2560

dataset_config:
  vqa2:
    depth_first: true
    use_features: true
    features:
      train:
      - /home/datasets/VizWiz/grid-feats-vqa/features/
      val:
      - /home/datasets/VizWiz/grid-feats-vqa/features/
      test:
      - /home/datasets/VizWiz/grid-feats-vqa/features/
    annotations:
      train:
      - ./datasets/vizwiz/annotations_grid/imdb_vizwiz_train.npy
      val:
      - ./datasets/vizwiz/annotations_grid/imdb_vizwiz_val.npy
      test:
      - ./datasets/vizwiz/annotations_grid/imdb_vizwiz_test.npy
    # Set to >= max number of features for the dataset
    max_features: 1024

optimizer:
  type: adam_w
  params:
    lr: 5e-05
    weight_decay: 0
    eps: 1e-09
    betas:
    - 0.9
    - 0.98

scheduler:
  type: multi_step
  params:
    use_warmup: true
    lr_steps:
    - 18000
    - 21600
    lr_ratio: 0.2
    warmup_iterations: 5400
    warmup_factor: 0.25

evaluation:
  metrics:
  - vqa_accuracy

training:
  seed: 42
  lr_scheduler: true
  clip_norm_mode: all
  clip_gradients: false
  max_grad_l2_norm: 5
  max_updates: 23600
  batch_size: 16
  task_size_proportional_sampling: true
  encoder_lr_multiply: 1
  early_stop:
    criteria: vqa2/vqa_accuracy
    minimize: false
  find_unused_parameters: true
