mmf_run config=mmf_configs/uniter_vizwiz/defaults.yaml \
	model=uniter \
	dataset=vqa2 \
	run_type=train \
	training.batch_size=16 \
    	training.log_interval=100 \
	training.checkpoint_interval=1000 \
    	training.evaluation_interval=1000 \
	checkpoint.resume_pretrained=True \
	checkpoint.resume_zoo=uniter.pretrained \
	training.find_unused_parameters=True
